import axios from "axios";
import React, { useEffect, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { Row, Col, Form, Button } from "react-bootstrap";
import VideoCard from "../Components/Videos/VideoCard";
import { baseURL } from "../Config/config";

function Videos() {
  const [videos, setVideos] = useState([]);
  const [videoId, setVideoId] = useState("");
  const [validated, setValidated] = useState(false);
  const navigate = useNavigate();

  const retrieveVideos = () => {
    axios
      .get(`${baseURL}/videos/all-videos`)
      .then((res) => {
        setVideos(res.data);
        console.log(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  useEffect(retrieveVideos, []);

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!videoId) {
      event.stopPropagation();
      setValidated(true);
      return;
    }

    setValidated(true);
    navigate(`/sign-kit/video/${videoId}`, { replace: false });
  };

  const handleClick = (videoId) => {
    navigate(`/sign-kit/video/${videoId}`, { replace: false });
  };

  const videoList = videos.map((video, index) => (
    <VideoCard key={index} video={video} handleClick={handleClick} />
  ));

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh', paddingTop: 85, color: 'var(--text)' }}>
      {/* ── Header ─────────────────────────────────────────────────── */}
      <section className="container text-center py-5">
        <h1 className="display-4 fw-bold mb-3">Explore <span className="gradient-text">Gallery</span></h1>
        <p className="lead" style={{ color: 'var(--muted)', maxWidth: 700, margin: '0 auto' }}>
          Welcome to the CodeCrafters showcase. Create, share, and explore ISL translations generated by our community using our advanced generative models.
        </p>
      </section>

      {/* ── Actions Row ────────────────────────────────────────────── */}
      <section className="container mb-5">
        <div className="row g-4 justify-content-center">
          
          {/* Create Video Card */}
          <div className="col-md-5">
            <div className="glass p-5 h-100 text-center d-flex flex-column align-items-center justify-content-center">
              <div style={{ fontSize: '2.5rem', marginBottom: 16 }}>🎬</div>
              <h3 className="fw-bold mb-3">Create New</h3>
              <p style={{ color: 'var(--muted)', fontSize: '0.9rem', marginBottom: 24 }}>
                Generate a new video sequence via text, speech, or file and get a unique ID to share.
              </p>
              <Link to='/codecrafters/create-video' className="btn-primary-glow text-decoration-none" style={{ width: 'auto' }}>
                Create Video
              </Link>
            </div>
          </div>

          {/* Open Video Card */}
          <div className="col-md-5">
            <div className="glass p-5 h-100 text-center d-flex flex-column align-items-center justify-content-center">
              <div style={{ fontSize: '2.5rem', marginBottom: 16 }}>🔍</div>
              <h3 className="fw-bold mb-3">Lookup ID</h3>
              <p style={{ color: 'var(--muted)', fontSize: '0.9rem', marginBottom: 24 }}>
                Have a video ID? Enter it below to fetch the generated ISL sequence instantly.
              </p>
              <Form noValidate validated={validated} onSubmit={handleSubmit} className="w-100">
                <Form.Control
                  required
                  type="text"
                  placeholder="Enter Video ID..."
                  value={videoId}
                  onChange={(e) => setVideoId(e.target.value)}
                  className="input-dark mb-3 w-100"
                  style={{ textAlign: 'center' }}
                />
                <button type="submit" className="btn-ghost" style={{ width: '100%', padding: '14px 28px' }}>
                  Open Request
                </button>
              </Form>
            </div>
          </div>

        </div>
      </section>

      {/* ── Public Feed ────────────────────────────────────────────── */}
      <section className="container py-5 border-top" style={{ borderColor: 'var(--border) !important' }}>
        <div className="text-center mb-5">
          <h2 className="fw-bold">Public Feed</h2>
          <p style={{ color: 'var(--muted)' }}>Browse sequences shared by the community.</p>
        </div>

        <div className="row g-4 justify-content-center">
          {videoList}
        </div>
      </section>
    </div>
  );
}

export default Videos;
